import turtle as t

t.setup(700, 700, 0, 0)
t.width(2)
t.pencolor("white")
t.bgcolor("black")

def rainbowloop():
    t.pencolor("brown")
    t.fd(7)
    t.rt(45)
    t.pencolor("maroon")
    t.fd(7)
    t.rt(5)
    t.pencolor("red")
    t.fd(7)
    t.rt(5)
    t.pencolor("orange")
    t.fd(7)
    t.rt(5)
    t.pencolor("gold")
    t.fd(7)
    t.rt(5)
    t.pencolor("yellow")
    t.fd(7)
    t.rt(5)
    t.pencolor("lightgreen")
    t.fd(7)
    t.rt(5)
    t.pencolor("turquoise")
    t.fd(7)
    t.rt(5)
    t.pencolor("cyan")
    t.fd(7)
    t.rt(5)
    t.pencolor("skyblue")
    t.fd(7)
    t.rt(5)
    t.pencolor("blue")
    t.fd(7)
    t.rt(5)
    t.pencolor("navy")
    t.fd(7)
    t.rt(5)
    t.pencolor("purple")
    t.fd(7)
    t.rt(5)
    t.pencolor("magenta")
    t.fd(7)
    t.rt(5)
    t.pencolor("violet")
    t.fd(7)
    t.rt(5)
rainbowloop()

for i in range (200):
    t.lt(30)
    rainbowloop()
    t.lt(70)
    rainbowloop()
    t.lt(30)
    rainbowloop()
    t.lt(70)
    rainbowloop()
    t.lt(30)
    rainbowloop()
    t.lt(70)
    



