import turtle as t

t.setup(1000, 1000, 0, 0)
t.speed(0)
t.width(2)
t.pencolor("white")
t.bgcolor("black")
t.penup()
t.goto(-100, -200)
t.pendown()

def rainbowloop():
    t.pencolor("red")
    t.fd(10)
    t.rt(40)
    t.pencolor("orange")
    t.fd(10)
    t.rt(5)
    t.pencolor("yellow")
    t.fd(10)
    t.rt(5)
    t.pencolor("lightgreen")
    t.fd(10)
    t.lt(40)
    t.pencolor("cyan")
    t.fd(10)
    t.rt(5)
    t.pencolor("blue")
    t.fd(10)
    t.pencolor("magenta")
    t.fd(10)

for i in range(200):
    rainbowloop()
    t.rt(90)
    rainbowloop()
    t.lt(180)
    rainbowloop()
    t.rt(91)
    rainbowloop()
    t.lt(180)
